application:
  port: 8000
  host: 0.0.0.0
database:
  host: "127.0.0.1"
  port: 5432
  database_name: "events"
  username: "postgres"
  password: "password"
  require_ssl: false
snowflake:
  start_millis: 1704067200000
  process_id: 0
  worker_id: 1